apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.8.3
  releaseName: ingress-nginx
  namespace: ingress-nginx
  valuesInline:
    controller:
      extraArgs:
        # Secret where the default ingress TLS cert (wildcard) lives: <namespace>/<secret_name>
        default-ssl-certificate: ingress-nginx/default-tls
      replicaCount: 2
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
          # Use private IP addressing
          service.beta.kubernetes.io/azure-load-balancer-internal: true
          # Specify the static IP from the AKS cluster's node subnet for the ingress controller's LoadBalancer (and DNS records)
          service.beta.kubernetes.io/azure-load-balancer-ipv4: REPLACE_ME

resources:
  # Front the ingress controller with an IPv6 LoadBalancer Service
  - service-ingress-nginx-controller-ipv6.yaml