apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: goldilocks
  repo: https://charts.fairwinds.com/stable
  version: 8.0.0
  releaseName: goldilocks
  namespace: goldilocks

namespace: goldilocks

resources:
  - goldilocks-ingress.yaml