apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base-8.0.0

patches:
# Apply the static IP addresses
- target:
    kind: Ingress
    name: goldilocks-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: goldilocks.example.com
