apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    g, "c27fa64c-216d-4910-913e-e6fba3e1b3e7", role:readonly
    g, "e75b5328-fbc3-4ded-a45c-96c4d3aaad19", role:admin

  # Alternatively, create a custom role, like this:
  #   p, role:org-admin, applications, *, */*, allow
  #   p, role:org-admin, clusters, get, *, allow
  #   p, role:org-admin, repositories, get, *, allow
  #   p, role:org-admin, repositories, create, *, allow
  #   p, role:org-admin, repositories, update, *, allow
  #   p, role:org-admin, repositories, delete, *, allow
  #   p, role:org-admin, projects, get, *, allow
  #   p, role:org-admin, projects, create, *, allow
  #   p, role:org-admin, projects, update, *, allow
  #   p, role:org-admin, projects, delete, *, allow
  #   p, role:org-admin, logs, get, *, allow
  #   p, role:org-admin, exec, create, */*, allow
  #   g, your-azure-group-id, role:org-admin  
  #   g, your-github-org:your-team, role:org-admin
