apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-notifications-controller
        resources:
          requests:
            cpu: 10m
            memory: 37M
          limits:
            cpu: 12m
            memory: 42M