apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
  url: https://localhost:8081
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      id: saml
      name: saml
      config:
        entityIssuer: https://localhost:8081/api/dex/callback
        ssoURL: https://login.microsoftonline.com/c5b7c008-6837-4fb0-b4ad-b491dd2dd926/saml2
        caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDOERDQ0FkaWdBd0lCQWdJUUxpeTUzcGlUM2FCSnJybmc2dks5dVRBTkJna3Foa2lHOXcwQkFRc0ZBREEwTVRJd01BWURWUVFEDQpFeWxOYVdOeWIzTnZablFnUVhwMWNtVWdSbVZrWlhKaGRHVmtJRk5UVHlCRFpYSjBhV1pwWTJGMFpUQWVGdzB5TXpFeU1qa3hOekUzDQpNRFJhRncweU5qRXlNamt4TnpFM01EUmFNRFF4TWpBd0JnTlZCQU1US1UxcFkzSnZjMjltZENCQmVuVnlaU0JHWldSbGNtRjBaV1FnDQpVMU5QSUVObGNuUnBabWxqWVhSbE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBczgyZkRXaHRKd25YDQpCb2NaK3FEOVhvV1ZpQTlIbFd5WWNZREFlQU1NckNIZXo1VmxXOWtlUFp3YkhuZTkxNFVPL3ZINWR1aUhieWhiZDJad1FVa2pJRDU3DQpsa1RKNk1YVnZpOEt1RW01anRuOGRiZlUvQ1IyMzdSeE9WUEZmTWh3SE9oMFR1cUJ3bEpELzNvZ2dQakVxQzRqYXU1bFhONnRWZExuDQpCWWZ0R2x3aUFuVzRTemhGNllsdC9ndzlySEdKTFh2QldPbWNRcHhPUGdYc1hNRFQwMG9oQ28rUXc1UTAxZlpTS3RPRG9RRHhXVVlqDQpVUVFkYzZSMlFYVUVjQU1HYllEWG94ZWNocUdwZjNEVEt6amQrRWxxVzhiMFNIV2R5NFQrdUVPemJ6Zis1SFRWTld4SHZUUG4wQ0h2DQowaHJjM3V0MG1xUDZxWlFFMjJCMklOZUNKUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQllROVgyU2VGSGVDS3RuM0ZiDQpuYkVVeGJZM1ZvR29lOEsvRm9JRGVMekpPRndFZ1pKNWFDY0ovVkY3bWRrYkFoS1ZRdytyUmwrM2RZY281RnNQOVBNeEtrWitPdURxDQpmWGVJU3Q2N3N5aXhnNlpLblpXM0pGaERSKzZHTktLUTVZU1V1aWVRUWJKYWE0dWkwWHhHZkVKSWxqdC9Ra0R3ZmlTRGZMcld3WjlwDQo1VGx1K3NvM2JuTUhmZlNLOVhFNm1YVDZMN2VUTFF3V0ZLN2pwcDVFdE1PRyt6bFQ2TDdEL0RSNzI5TjVVbitFZWtFQ0xVaFZSdi9EDQowQUVxZEgwVFRDSUFZK3BtcE1ZODhMUWIvOThjZE9mTXJBMVJmTzF4QUhvOWsxMkJhbzhPRWFlV0NvODhaWC9FMlJsaFRzM05XZHZZDQpodHo5c1Z3akNSTU5oRmhsaldlRQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
        redirectURI: https://localhost:8081/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: Group