apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Install the AWX operator. Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.8.0
  # Tell the operator to create our AWX instance
  - awx.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.8.0

# Specify a namespace in which to install AWX (should match your environment)
namespace: replace_in_overlay

# Specify a name for the AWX instance (should match your environment)
patches:
- target:
    kind: AWX
  patch: |-
    - op: replace
      path: /metadata/name
      value: "replace_in_overlay"